UXAR2-2
KT-devs/p-sm-uxair2 pull request #2
Opened 2023-03-15 08:32 UTC by WDissney

Смотреть config-server

2023-03-18 15:32 UTC, Vdim4ik commented on config-service/src/main/java/main/ConfigurationServerApplication.java
> +package main;
Папки

2023-03-18 19:20 UTC, WDissney commented on config-service/src/main/java/main/ConfigurationServerApplication.java
> +package main;
Поменял

2023-03-19 16:47 UTC, pdasilem requested changes
Добавить конфиги: local, dev
Выделить общий ямл для всех сервис

2023-03-23 17:17 UTC, Vdim4ik approved these changes

2023-03-23 17:19 UTC, GK2128 approved these changes

2023-03-25 13:53 UTC, Vdim4ik approved these changes

2023-03-28 16:34 UTC, pdasilem approved these changes

2023-03-28 16:34 UTC, merged