Uxar2 19
KT-devs/p-sm-uxair2 pull request #5
Opened 2023-03-16 16:50 UTC by reduss21

я не могу понять в чем проблема при инициализации liqui не добавляет в postgres базу shem'у таблицы

2023-03-23 11:27 UTC, pdasilem requested changes

2023-03-23 11:27 UTC, pdasilem commented on db-migration/src/main/resources/db/changelog/changeset/seat-table_changeset.yaml
> +databaseChangeLog:
это из другой таски

2023-03-26 17:37 UTC, Vdim4ik approved these changes

2023-03-26 17:41 UTC, WDissney approved these changes

2023-03-28 15:21 UTC, pdasilem approved these changes

2023-03-28 15:22 UTC, merged