v1.0
KT-devs/p-sm-uxair2 pull request #7
Opened 2023-03-18 12:16 UTC by GK2128

2023-03-18 12:17 UTC, WDissney approved these changes
Perfecto!

2023-03-18 12:18 UTC, WDissney approved these changes
All good!

2023-03-18 15:33 UTC, Vdim4ik approved these changes

2023-03-19 16:23 UTC, pdasilem requested changes
добавить описание (общий коммент)

2023-03-19 16:23 UTC, pdasilem commented on flight-service/src/main/java/ru/uxair/flight/entity/SeatCategory.java
> +    FIRST,
Добавить описание

2023-03-21 16:24 UTC, pdasilem approved these changes

2023-03-21 16:24 UTC, merged